# Generated by Django 6.0.7 on 2026-07-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='nouveau', max_length=50)),
                ('client_name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('city_country', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=50)),
                ('project_type_custom', models.CharField(blank=True, max_length=200, null=True)),
                ('context_description', models.TextField()),
                ('primary_objective', models.TextField()),
                ('target_audience', models.TextField()),
                ('target_audience_chips', models.JSONField(default=list)),
                ('main_title', models.CharField(max_length=200)),
                ('full_text_content', models.TextField()),
                ('style_preferences', models.JSONField(default=list)),
                ('preferred_colors', models.CharField(max_length=200)),
                ('avoid_colors', models.CharField(max_length=200)),
                ('technical_format', models.CharField(max_length=50)),
                ('custom_dimensions', models.CharField(blank=True, max_length=200, null=True)),
                ('usage_type', models.CharField(max_length=20)),
                ('budget_range', models.CharField(max_length=50)),
                ('desired_delivery_date', models.CharField(max_length=50)),
                ('critical_deadline', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_links', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(default=list)),
                ('accept_process', models.BooleanField(default=False)),
                ('accept_deadlines', models.BooleanField(default=False)),
                ('designer_notes', models.TextField(blank=True, null=True)),
                ('quoted_price_fcfa', models.IntegerField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project_type', models.CharField(max_length=50)),
                ('technical_format', models.CharField(max_length=50)),
                ('custom_dimensions', models.CharField(blank=True, max_length=200, null=True)),
                ('default_main_title', models.CharField(max_length=200)),
                ('default_full_text_content', models.TextField()),
                ('style_preferences', models.JSONField(default=list)),
                ('preferred_colors', models.CharField(max_length=200)),
                ('avoid_colors', models.CharField(max_length=200)),
                ('default_budget_range', models.CharField(max_length=50)),
                ('suggested_price_fcfa', models.IntegerField()),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
    ]
