# Generated by Django 6.0.7 on 2026-08-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('price_estimate', models.CharField(blank=True, max_length=100, null=True)),
                ('accent_hex', models.CharField(default='#816C07', max_length=50)),
                ('features', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_stock', 'En stock'), ('available_24_48h', 'Disponible 24-48h'), ('on_order', 'Sur commande'), ('unavailable', 'Indisponible')], default='on_order', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
