# Generated by Django 6.0.7 on 2026-08-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_update_superuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='accept_deadlines',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='accept_process',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='avoid_colors',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='budget_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='city_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='context_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='desired_delivery_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='full_text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='main_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='preferred_colors',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='primary_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='style_preferences',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='target_audience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='technical_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='usage_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
