# Generated by Django 6.0.7 on 2026-08-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_brief_accept_deadlines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100, verbose_name="Nom de l'outil")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'utilisation")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': "Utilisation d'outil",
                'verbose_name_plural': 'Statistiques Outils',
                'ordering': ['-created_at'],
            },
        ),
    ]
