# Generated by Django 6.0.7 on 2026-08-10 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_brief_target_audience_chips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organisation / Marque')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='brief',
            options={'ordering': ['-created_at'], 'verbose_name': 'Brief & Projet', 'verbose_name_plural': 'Briefs & Projets'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projet Portfolio', 'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit Boutique', 'verbose_name_plural': 'Hadara Store (Produits)'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Modèle de Brief', 'verbose_name_plural': 'Modèles de Brief'},
        ),
        migrations.AlterField(
            model_name='brief',
            name='accept_deadlines',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Délais Validés'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='accept_process',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Processus Validé'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True, verbose_name='Analyse IA Hadara'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Pièces Jointes'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='avoid_colors',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Couleurs à Éviter'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='budget_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fourchette de Budget'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='city_country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ville / Pays'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='context_description',
            field=models.TextField(blank=True, null=True, verbose_name='Contexte & Description'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de Création'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='critical_deadline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Délai Critique'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='custom_dimensions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dimensions Spécifiques'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='designer_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes du Designer'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='desired_delivery_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date de Livraison Souhaitée'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse Email'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='full_text_content',
            field=models.TextField(blank=True, null=True, verbose_name='Textes Inclus'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='main_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre Principal'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organisation / Marque'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='preferred_colors',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Couleurs Préférées'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='primary_objective',
            field=models.TextField(blank=True, null=True, verbose_name='Objectif Principal'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type de Projet'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='project_type_custom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Type de Projet Personnalisé'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='quoted_price_fcfa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Devis Estimé (FCFA)'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='reference_links',
            field=models.TextField(blank=True, null=True, verbose_name='Liens de Référence'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='status',
            field=models.CharField(default='nouveau', max_length=50, verbose_name='Statut du Projet'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='style_preferences',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Styles Souhaités'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='target_audience',
            field=models.TextField(blank=True, null=True, verbose_name='Cible Visée'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='technical_format',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Format Technique'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='usage_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Type d'Usage"),
        ),
        migrations.AlterField(
            model_name='brief',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='badge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Badge Visuel'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='Image du projet (URL ou Upload)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='price_estimate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tarif Indicatif'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre du projet'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='En Vedette'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Image (URL ou Fichier)'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='status',
            field=models.CharField(choices=[('in_stock', 'En stock'), ('available_24_48h', 'Disponible 24-48h'), ('on_order', 'Sur commande'), ('unavailable', 'Indisponible')], default='on_order', max_length=20, verbose_name='Statut Stock'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible en Boutique'),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='template',
            name='custom_dimensions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dimensions'),
        ),
        migrations.AlterField(
            model_name='template',
            name='project_type',
            field=models.CharField(max_length=50, verbose_name='Type de projet'),
        ),
        migrations.AlterField(
            model_name='template',
            name='technical_format',
            field=models.CharField(max_length=50, verbose_name='Format technique'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre du modèle'),
        ),
        migrations.AlterField(
            model_name='template',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name="Nombre d'utilisations"),
        ),
        migrations.CreateModel(
            name='BillingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=30, unique=True, verbose_name='Numéro de document')),
                ('doc_type', models.CharField(choices=[('proforma', 'Proforma'), ('facture', 'Facture'), ('avoir', 'Avoir')], default='proforma', max_length=15, verbose_name='Type')),
                ('payment_status', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de paiement'), ('acompte', 'Acompte reçu'), ('partiel', 'Partiellement payé'), ('paye', 'Payé ✅'), ('en_retard', 'En retard 🔴'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut de paiement')),
                ('billing_client_name', models.CharField(blank=True, max_length=200, verbose_name='Client (snapshot)')),
                ('billing_organization', models.CharField(blank=True, max_length=200, verbose_name='Organisation (snapshot)')),
                ('billing_address', models.TextField(blank=True, verbose_name='Adresse (snapshot)')),
                ('billing_email', models.CharField(blank=True, max_length=200, verbose_name='Email (snapshot)')),
                ('billing_whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp (snapshot)')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Sous-total (FCFA)')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Remise (FCFA)')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total net (FCFA)')),
                ('currency', models.CharField(default='XOF', max_length=5, verbose_name='Devise')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_documents', to='api.brief', verbose_name='Brief / Projet')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_documents', to='api.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Document de Facturation',
                'verbose_name_plural': '💰 Facturation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=500, verbose_name='Désignation / Prestation')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Quantité')),
                ('unit_price', models.PositiveIntegerField(default=0, verbose_name='Prix unitaire (FCFA)')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.billingdocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Ligne de facturation',
                'verbose_name_plural': 'Lignes de facturation',
            },
        ),
        migrations.AddField(
            model_name='brief',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefs', to='api.client', verbose_name='Client (Facturation)'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(verbose_name='Montant encaissé (FCFA)')),
                ('method', models.CharField(choices=[('wave', '🟣 Wave'), ('orange_money', '🟠 Orange Money'), ('especes', '💵 Espèces'), ('virement', '🏦 Virement'), ('cheque', '📋 Chèque'), ('autre', '💳 Autre')], default='wave', max_length=20, verbose_name='Méthode de paiement')),
                ('reference_code', models.CharField(blank=True, max_length=200, verbose_name='Référence (ex: WAVE-XXXXXX)')),
                ('payment_date', models.DateField(verbose_name='Date du paiement')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Note (ex: Acompte)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.billingdocument', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['payment_date'],
            },
        ),
    ]
