# Generated by Django 6.0.7 on 2026-08-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_client_alter_brief_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdocument',
            name='payment_status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'Non payé'), ('partiellement_paye', 'Partiellement payé'), ('paye', 'Payé ✅'), ('en_retard', 'En retard 🔴'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut de paiement'),
        ),
    ]
