# Generated by Django 6.0.7 on 2026-08-18 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Provider IA',
                'verbose_name_plural': 'Providers IA',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('cost_per_input_token', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cost_per_output_token', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_json_mode', models.BooleanField(default=False)),
                ('supports_tool_calling', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='hadara_ai.aiprovider')),
            ],
            options={
                'verbose_name': 'Configuration de Provider',
                'verbose_name_plural': 'Configurations de Providers',
                'unique_together': {('provider', 'model_id')},
            },
        ),
    ]
