# Generated by Django 6.0.7 on 2026-08-18 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadara_ai', '0002_prompttemplate_promptversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('tools_allowed', models.JSONField(blank=True, default=list, verbose_name='Outils autorisés')),
                ('max_iterations', models.IntegerField(default=10)),
                ('max_tool_calls', models.IntegerField(default=20)),
                ('max_execution_time_s', models.IntegerField(default=120)),
                ('max_cost_usd', models.DecimalField(decimal_places=4, default=0.5, max_digits=10)),
                ('temperature', models.FloatField(default=0.2)),
                ('require_confirmation', models.BooleanField(default=False, verbose_name='Exiger confirmation avant exécution')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_fallback_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_fallback1', to='hadara_ai.aiproviderconfig', verbose_name='Modèle fallback 1')),
                ('model_fallback_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_fallback2', to='hadara_ai.aiproviderconfig', verbose_name='Modèle fallback 2')),
                ('model_primary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents_primary', to='hadara_ai.aiproviderconfig', verbose_name='Modèle principal')),
                ('prompt_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='hadara_ai.prompttemplate', verbose_name='Template de prompt')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='hadara_ai.promptversion', verbose_name='Version de prompt (vide = version active)')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['name'],
            },
        ),
    ]
