# Generated by Django 6.0.7 on 2026-08-18 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadara_ai', '0003_agentdefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('duration_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retention_policy', models.CharField(choices=[('full', 'Full'), ('redacted', 'Redacted'), ('metadata_only', 'Metadata Only')], default='metadata_only', max_length=20)),
                ('prompt_content', models.TextField(blank=True, null=True)),
                ('response_content', models.TextField(blank=True, null=True)),
                ('brief_id', models.CharField(blank=True, max_length=50)),
                ('client_id', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='hadara_ai.agentdefinition')),
                ('parent_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_executions', to='hadara_ai.aiexecution')),
            ],
            options={
                'verbose_name': 'Exécution IA',
                'verbose_name_plural': 'Exécutions IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.UUIDField(db_index=True)),
                ('agent_slug', models.CharField(blank=True, max_length=100)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('brief_id', models.CharField(blank=True, max_length=50)),
                ('client_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Log de coût',
                'verbose_name_plural': 'Logs de coûts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_slug', 'created_at'], name='hadara_ai_c_agent_s_35c668_idx'), models.Index(fields=['brief_id'], name='hadara_ai_c_brief_i_63db2f_idx'), models.Index(fields=['client_id'], name='hadara_ai_c_client__38eb9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.UUIDField(db_index=True)),
                ('tool_name', models.CharField(max_length=100)),
                ('arguments', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='hadara_ai.aiexecution')),
            ],
            options={
                'verbose_name': "Exécution d'outil",
                'verbose_name_plural': "Exécutions d'outils",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('agent_slug', models.CharField(blank=True, max_length=100)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('total_calls', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('total_tool_calls', models.IntegerField(default=0)),
                ('avg_duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Log d'utilisation",
                'verbose_name_plural': "Logs d'utilisation",
                'ordering': ['-date'],
                'unique_together': {('date', 'agent_slug', 'provider', 'model')},
            },
        ),
        migrations.AddIndex(
            model_name='aiexecution',
            index=models.Index(fields=['trace_id', 'created_at'], name='hadara_ai_a_trace_i_58b368_idx'),
        ),
        migrations.AddIndex(
            model_name='aiexecution',
            index=models.Index(fields=['agent', 'created_at'], name='hadara_ai_a_agent_i_04f55e_idx'),
        ),
        migrations.AddIndex(
            model_name='aiexecution',
            index=models.Index(fields=['provider', 'created_at'], name='hadara_ai_a_provide_c36427_idx'),
        ),
        migrations.AddIndex(
            model_name='aiexecution',
            index=models.Index(fields=['model', 'created_at'], name='hadara_ai_a_model_a2b29f_idx'),
        ),
        migrations.AddIndex(
            model_name='aiexecution',
            index=models.Index(fields=['brief_id'], name='hadara_ai_a_brief_i_96f0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['trace_id', 'created_at'], name='hadara_ai_t_trace_i_6c4b43_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['tool_name', 'created_at'], name='hadara_ai_t_tool_na_78286c_idx'),
        ),
    ]
