# Generated by Django 6.0.7 on 2026-08-19 01:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadara_ai', '0004_aiexecution_costlog_toolexecution_usagelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefAIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brief_id', models.CharField(db_index=True, max_length=20)),
                ('tenant_id', models.CharField(db_index=True, default='default', max_length=50)),
                ('agent', models.CharField(default='brief_analyst', max_length=50)),
                ('model', models.CharField(default='llama-3.1-8b-instant', max_length=100)),
                ('prompt_version', models.CharField(default='v1', max_length=50)),
                ('score_completude', models.IntegerField(default=0)),
                ('complexite_percue', models.IntegerField(default=0)),
                ('decision_recommandee', models.CharField(default='ACCEPTER SOUS RÉSERVE', max_length=50)),
                ('statut_brief', models.CharField(default='exploitable_sous_reserve', max_length=50)),
                ('niveau_priorite', models.CharField(default='Normal', max_length=20)),
                ('raison_decision', models.TextField(blank=True, default='')),
                ('informations_manquantes', models.JSONField(default=list)),
                ('questions_client', models.JSONField(default=list)),
                ('risques', models.JSONField(default=list)),
                ('pricing_prix_min', models.IntegerField(default=0)),
                ('pricing_prix_max', models.IntegerField(default=0)),
                ('pricing_heures_min', models.IntegerField(default=0)),
                ('pricing_heures_max', models.IntegerField(default=0)),
                ('client_fidelite', models.CharField(default='nouveau', max_length=20)),
                ('client_nb_projets', models.IntegerField(default=0)),
                ('client_solde_du', models.IntegerField(default=0)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('duration_ms', models.IntegerField(default=0)),
                ('full_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analyse IA de brief',
                'verbose_name_plural': 'Analyses IA de briefs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brief_id', '-created_at'], name='hadara_ai_b_brief_i_150b9b_idx'), models.Index(fields=['tenant_id', '-created_at'], name='hadara_ai_b_tenant__35bb36_idx'), models.Index(fields=['agent', '-created_at'], name='hadara_ai_b_agent_453a84_idx')],
            },
        ),
    ]
