# Generated by Django 6.0.7 on 2026-08-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadara_ai', '0005_briefaianalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefaianalysis',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('fallback', 'Fallback')], db_index=True, default='completed', max_length=20),
        ),
    ]
