# Generated by Django 6.0.7 on 2026-08-19 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadara_ai', '0006_briefaianalysis_analysis_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brief_id', models.CharField(db_index=True, max_length=100)),
                ('workflow_name', models.CharField(default='full_pipeline', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('partial', 'Partiellement complété'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('current_step', models.CharField(blank=True, default='', max_length=50)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=2)),
                ('total_duration_ms', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIWorkflowStepExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=50)),
                ('step_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('skipped', 'Ignoré'), ('retrying', 'Nouvel essai')], default='pending', max_length=20)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='hadara_ai.aiworkflowexecution')),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('workflow', 'step_name')},
            },
        ),
    ]
