# Generated by Django 6.0.7 on 2026-08-19 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadara_ai', '0007_aiworkflowexecution_aiworkflowstepexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgentUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brief_id', models.CharField(db_index=True, max_length=100)),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('agent', models.CharField(db_index=True, max_length=50)),
                ('model', models.CharField(default='', max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('duration_ms', models.IntegerField(default=0)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('brief_status', models.CharField(blank=True, default='', max_length=20)),
                ('brief_accepted', models.BooleanField(default=False)),
                ('quoted_price_fcfa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIDailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_workflows', models.IntegerField(default=0)),
                ('completed_workflows', models.IntegerField(default=0)),
                ('failed_workflows', models.IntegerField(default=0)),
                ('partial_workflows', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('total_tokens', models.IntegerField(default=0)),
                ('avg_duration_ms', models.IntegerField(default=0)),
                ('briefs_analyzed', models.IntegerField(default=0)),
                ('briefs_accepted', models.IntegerField(default=0)),
                ('revenue_attributed_fcfa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
